version: "3"


services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  rest_db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: "rest_db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  rest:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python /usr/src/supRest/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/supRest
    ports:
      - 8000:8000
    depends_on:
      - rest_db
volumes:
  postgres_data:
