# Generated by Django 3.2.7 on 2021-11-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutionOfProblem', models.TextField(max_length=255, verbose_name='решение проблемы')),
                ('dateOfAnswer', models.DateTimeField(auto_now_add=True, verbose_name='дата ответа')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.answer', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('incident', models.TextField(max_length=255, verbose_name='инцидент')),
                ('dateOfIncident', models.DateTimeField(auto_now=True, verbose_name='дата запроса')),
                ('is_done', models.BooleanField(default=True, verbose_name='состояние запроса')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.answer', verbose_name='ответ')),
                ('parentTicket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket', verbose_name='Родитель запроса')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
    ]
